### ISSUE TITLE
Suchfunktion

### ISSUE THREAD

**Issue by HaMster21** [FlyHinotori/autopilot#19]
Die Suchfunktion soll zentraler Navigationspunkt sein können. Sie wird durch ein Eingabefeld dargestellt in dem der Nutzer seine Suchanfrage eingeben kann. 

Suchergebnisse werden als Latin-1 String erwartet und ausgewertet. Ergebisse werden in einer aufklappenden Liste direkt unter der Suchleiste dargestellt. Ergebnisse werden per Klick oder per Tastatur ausgewählt, das entsprechende Event führt zu einer entsprechenden Ansicht in der Hauptanzeige mit vorher ausgewählten Datensatz als aktuell ausgewähltem.

Die Suche ist per Tastenkombination Strg+F aus jedem Dialog zu erreichen. Wenn das Suchfeld leer ist, werden die vorherigen Suchen angezeigt.

Gesucht wird per [https://de.wikipedia.org/wiki/Unscharfe_Suche](unscharfer Suche) in allen Kunden-, Rechnungs- und Termindatensätzen. Inventar wird nicht berücksichtigt. (Idee aus #17) Weiterführende Details [im englischen Wiki-Eintrag](https://en.wikipedia.org/wiki/Approximate_string_matching) zum Thema.

Damit die Daten in der Datenbank von den nötigen Transformationen der Strings für die unscharfe Suche nicht verändert werden müssen, werden alle relevanten Daten geladen und vorbereitet während der Splashscreen angezeigt wird.

Referenzen:
- [Codeproject-Artikel mit LINQ für Fuzzy Search](http://www.codeproject.com/Articles/36869/Fuzzy-Search)
- [FuzzyString Projekt auf Codeproject](https://fuzzystring.codeplex.com/)
- [StackOverflow Diskussion mit Fokus auf Geschwindigkeit](http://stackoverflow.com/questions/5972289/fast-dynamic-fuzzy-search-over-100k-strings-in-c-sharp)

**Comment by HaMster21** [comment]
Ähnliche Dinge werden auch schon in #12 aufgezeigt

**Comment by BunnyBuster** [comment]
Anmerkung:
Um die Unscharfe Suche in der Applikation zu benutzen, muss jeder Datensatz nach dem gesucht werden soll (der gefunden werden soll), beim Speichern auch als "Fuzzy-String" abgelegt werden.
Bei der Suche wandelt man den Suchbegriff zum "Fuzzy-String" um und sucht diesen in der Datenbank.

Speichert man den "Fuzzy-String" nicht, muss man bei der Suche den kompletten Datenbestand in den Speicher laden, den "Fuzzy-String" erstellen und kann dann danach suchen. Das könnte man mit dem Splash-Screen  #18 überbrücken. :)

**Comment by HaMster21** [comment]
Vielleicht hätte ich mir das doch besser schon mal angelesen^^

Ich würde mich jedenfalls nicht darum streiten das zu machen, aber ich halte das für ein tolles Usability Feature. Und da wir wohl keine Datenberge für die Demonstrationen aufhäufen werden würde ich das schon umsetzen wollen.

Ich guck morgen mal ob ich was finde das sowas schon kann.

**Comment by BunnyBuster** [comment]
brauchst nicht lange suchen: http://dotnet-snippets.de/snippet/fuzzy-suche/1145

Je länger ich darüber nachdenke, desto besser finde ich die Idee mit dem Splash-Screen. Viele Daten werden wir ja nicht haben. :)

**Comment by HaMster21** [comment]
Das stimmt, das mit dem Splash find ich auch gut. Muss der nur nachher auch noch gut aussehen, das dann wieder in #18 mündet ^^

**Comment by cerveza41** [comment]
Jo, super Idee :+1: Wir dürfen aber nicht vergessen die Fuzzy-Strings zur Laufzeit aktuell zu halten
