### ISSUE TITLE
Integration mit MS SQL

### ISSUE THREAD

**Issue by HaMster21** [FlyHinotori/autopilot#2]
Als Datenbackend wollten wir MS SQL verwenden. Für C# ist dafür wahrscheinlich das Entity Framework am besten geeignet. Entsprechende Abhängigkeiten werden per NuGet Paket eingeholt

**Comment by BunnyBuster** [comment]
Haben wir hinbekommen. Schließen?!

**Comment by HaMster21** [comment]
Wenn das nachher im master ist ;)

Scheint mir auch sehr ähnlich wie #7

**Comment by HaMster21** [comment]
Oh, das ist nicht mehr auf meinem Radar gewesen^^
