### ISSUE TITLE
Stammdatenseite

### ISSUE THREAD

**Issue by HaMster21** [FlyHinotori/autopilot#20]
Zur Verwaltung der Stammdaten braucht es eine eigene Seite. Dort werden in verschiedenen Kategorien bestehende Datensätze angezeigt und veränderbar gemacht, neue können hinzugefügt werden. Beziehungen zwischen Stammdaten werden hardcodiert und sind nicht veränderbar. 

Stammdaten die auszufüllen sind, können die folgenden sein:
- Flugzeughersteller
- Flugzeugtyp
- Triebwerksarten
- Positionen
- Positionsarten
- Status
- Statusgruppen
- Terminarten
- Ablehnungsgründe
- Mahnstufen
- Auftragsarten
- Kundengruppen
- Anreden
- Titel
- Flughäfen
- Flugzeuge
- Personal
- Kunden
- Lizenz

Die Stammdaten füllen die Auswahlfelder für die Dialoge mit denen der Benutzer durch die Aufträge geführt wird.

Auf der eigenen Seite werden die einzelnen Stammdaten zunächst als Kacheln angezeigt. Ein Klick auf eine Kachel öffnet dann eine Liste der Stammdaten der entsprechenden Auswahl. Verbindungen zu anderen Stammdaten werden dort ebenfalls abgebildet. 

Die Darstellung hängt unmittelbar an der Datenbank, alle Daten die dort dargestellt werden kommen aus der entsprechenden Tabelle. Hinzufügen und Löschen von Daten verändert auch die Inhalte der Datenbank. Datentypüberprüfung ist bereits während der Eingabe aktiv, dadurch sollen fehlerhafte Einträge vermieden werden.

**Comment by HaMster21** [comment]
Ich muss mir hier noch ausdenken wie ich das mal in die GUI packe...

**Comment by BunnyBuster** [comment]
das kann ich dir abnehmen...
https://slack-files.com/files-tmb/T03PT0TKY-F051R4F8N-8f57372aa6/pasted_image_at_2015_05_26_07_38_pm_720.png
...die beiden unteren Fenster.

**Comment by HaMster21** [comment]
Wenn das noch etwas größer und lesbar wäre... ^^

**Comment by BunnyBuster** [comment]
STRG und Mausrad
STRG und +
...

**Comment by HaMster21** [comment]
Wie man vergrößert weiß ich, leider kann man mit Alt und Mausrad das Schriftbild nicht leserlicher machen :laughing: 

Wenn ich nicht so müde wäre könnte ich das sicher auch noch so ;)

**Comment by BunnyBuster** [comment]
ich werde morgen dann mal die DB mit Stammdaten füllen, sodass wir was zum spielen haben. 
Oder drängt sich jemand anderes auf?

gehe jetzt schlafen, bis morgen...

**Comment by HaMster21** [comment]
Datenbanken sind Teufelswerk und gehören geächtet!

**Comment by cerveza41** [comment]
Ich finde den Begriff "Inventar" ist diesem Kontext etwas zu eng gefasst. "Stammdaten" ist da schon passender

**Comment by cerveza41** [comment]
Aufdrängen würde ich mich auch nicht. Es ist genug Arbeit für alle da :hammer:

**Comment by HaMster21** [comment]
Finde mal für Stammdaten ein Symbol für die GUI... :hushed:

**Comment by cerveza41** [comment]
Spontan fällt mir eine Mappe oder ein Zylinder (Datenbanksymbol) ein.

**Comment by BunnyBuster** [comment]
Mit den Stammdaten wären wir dann ja fast durch. Fehlen nur noch die Bilder für die Flugzeuge.
Habt ihr euch mal die Stammdatenseite "Flugzeuge" angeschaut? Wollen wir diese so oder so ähnlich lassen? 
Dann würde ich nämlich morgen mal sehen, dass da noch ein paar Bildchen in die DB kommen.

**Comment by cerveza41** [comment]
Ich finde es okay so
