### ISSUE TITLE
Entity Framework beim Programmstart laden

### ISSUE THREAD

**Issue by cerveza41** [FlyHinotori/autopilot#35]
Das Laden des Entity Framework ist mit einer merkbaren Verzögerung verbunden. Es sollte während des Splashscreens einmal geladen und global zur Verfügung gestellt werden. Ansichten, die Daten aus dem EF brauchen, müssen dann nur noch die nötigen Tabellen-Objekte aktualisieren

**Comment by cerveza41** [comment]
An diversen Stellen hab ich nun gelesen, dass es keine gute Praxis ist, ein DBContext Object (AutopilotEntities) global vorzuhalten ( [siehe hier](http://stackoverflow.com/questions/5663754/entity-framework-4-lifespan-scope-of-context-in-a-winform-application) ). 

Stattdessen soll nur der erste Aufruf von `new AutopilotEntities` etwas länger dauern. Weitere Aufrufe haben eine kaum spürbare Auswirkung auf die Performance.

**Comment by HaMster21** [comment]
Was ist mit _eine Entity pro Tabelle_, wie ihr das schon mal vorgeschlagen hattet? Vielleicht gibts da ja schon was was man laden kann und dann im Programm die Abläufe flüssiger gestalten könnte?

**Comment by BunnyBuster** [comment]
Dann bin ich doch eher für eine "Sanduhr" oder ein Hinweisfenster "Bitte etwas Geduld, Stammdaten werden geladen".
Für Aufträge, Termine,...sollten wir dann jeweils ein eigenständiges Entity bauen.

**Comment by HaMster21** [comment]
Ich sach mal ich halte mich da raus. Ich wollte mich nicht unbedingt ins EF einarbeiten, das überlass ich gern euch^^
