### ISSUE TITLE
Auftrag anlegen ohne Flugzeugwunsch

### ISSUE THREAD

**Issue by BunnyBuster** [FlyHinotori/autopilot#47]
Wird bei der Anlage eines Auftrages der Flugzeugwunsch vergessen, erscheint beim Speichern zwar eine Fehlermeldung, aber der Auftrag wird trotzdem angelegt (ohne Flugzeug).

**Comment by cerveza41** [comment]
Steht auf der Liste. Die Pflichtfeldprüfung beim Anlegen des Angebots ist noch nicht perfekt

**Comment by HaMster21** [comment]
Alles Teil der `Optimierungen` :laughing:

**Comment by cerveza41** [comment]
Dies hat sich mit #64 ebenfalls erledigt. Es wird nun vor dem Speichern geguckt, ob ein Flugzeugtyp ausgewählt wurde
