### ISSUE TITLE
Rechnungs-relevante Daten müssen redundant gespeichert werden

### ISSUE THREAD

**Issue by HaMster21** [FlyHinotori/autopilot#52]
Hier darf keine Deduplikation vorgenommen werden, weil das Finanzamt auch in 100 Jahren noch nachvollziehen können will was wir da in der Rechnung geschrieben haben.

Alle Daten müssen ausdrücklich in den Rechnungsdaten stehen, keine Referenzen

**Comment by BunnyBuster** [comment]
Hier gibt es meiner Meinung nach nur zwei Lösungen:
1. Wir lassen das Datenbankmodell so wie es ist und speichern (archivieren) die Rechnung als PDF in der Datenbank (als BLOB direkt am Auftrag). Dies hat den Vorteil, dass Statistiken viel leichter zu erstellen sind und der ganze Vorgang nicht unnötig aufgebläht wird. Es muss dann natürlich sichergestellt werden, dass in der Applikation kein Datenbankinhalt gelöscht werden kann. Dies sollte aber generell so sein.
1a. Anpassung der Tabelle "auftrag": wenn eine Rechnung als bezahlt gekennzeichnet wird, werden Kundenanschrift, ... in extra Spalten geschrieben
2. Das Datenbankmodell muss so angepasst werden, dass der komplette Inhalt der Rechnung in der Datenbank nochmals abgelegt wird - Flugzeug, Crew, Kundenanschrift,...Dies erschwert dann sicherlich die Anzeige und das Bebuchen von lebenden und abgeschlossenen Aufträgen in einer Übersicht. Das Erstellen von Statistiken wird dann auch sehr komplex.

**Comment by cerveza41** [comment]
Ich würde vorschlagen dieses issue generell zurück zu stellen, da es nicht teil des pflichtenhefts ist
