### ISSUE TITLE
Schaltfläche "Einstellungen" löschen

### ISSUE THREAD

**Issue by BunnyBuster** [FlyHinotori/autopilot#69]
Da sich hinter der Schaltfläche "Einstellungen" nicht wirklich was verbirgt, würde ich diese ausblenden.

**Comment by cerveza41** [comment]
okay :+1:

**Comment by BunnyBuster** [comment]
Ich mach das im PR "Auftrag Abwicklung"!

**Comment by HaMster21** [comment]
Ich hab schon hin und wieder mal überlegt was da rein sollte, bin aber auf nichts sinnvolles gekommen...
