### ISSUE TITLE
Datenbankschnittstellen mit dem Entity Framework

### ISSUE THREAD

**Issue by HaMster21** [FlyHinotori/autopilot#7]

**Comment by BunnyBuster** [comment]
Haben wir hinbekommen. Schließen?!

**Comment by HaMster21** [comment]
Der geht erst zu wenn das im master ist ;)

**Comment by HaMster21** [comment]
und das hier hat mit #24 zu tun

**Comment by HaMster21** [comment]
Übrigens hab ich grad einen Artikel dazu bei heise gelesen.
http://heise.de/-2733185
Ich bin noch nicht sicher ob das für uns interessant ist

**Comment by BunnyBuster** [comment]
Ist wohl eher nicht interessant für uns. Es ist dort die Rede von konkurrierenden Schreibzugriffen auf einen Datensatz und dessen Umgang damit. Dies sollte bei uns nicht vorkommen, da wir eine SingleUserAnwendung bauen.
